- title: "Doing More with Less: Orchestrating Serverless Applications without an Orchestrator"
  conf: "NSDI'23"
  presenter: Nanxiang Li
  date: June 14, 2024.
  time: 4:30 p.m.
  location: Room CS119 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/CC0WbDFd2HvR
    - title: Slides
      url:  /slides/Doing More with Less.pdf
- title: "ServerlessLLM: Locality-Enhanced Serverless Inference for Large Language Models"
  conf: "OSDI'24"
  presenter: Haodong Tian
  date: June 7, 2024.
  time: 4:30 p.m.
  location: Room CS119 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/HLStYbQc263w
    - title: Slides
      url:  /slides/ServerlessLLM.pdf
- title: "CoActo: CoActive Neural Network Inference Offloading with Fine-grained and Concurrent Execution"
  conf: "MobiSys'24"
  presenter: Ye Wan
  date: May 17, 2024.
  time: 4:30 p.m.
  location: Room CS119 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/XBBCY5CVghPp
    - title: Slides
      url:  /slides/Coacto.pdf
- title: "Optimizing Dynamic Neural Networks with Brainstorm"
  conf: "OSDI'23"
  presenter: Mengyang Liu
  date: May 10, 2024.
  time: 4:30 p.m.
  location: Room CS119 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/yU1O1dnZaGz2
    - title: Slides
      url:  /slides/Brainstorm.pdf
- title: "No Provisioned Concurrency: Fast RDMA-codesigned Remote Fork for Serverless Computing"
  conf: "OSDI'23"
  presenter: Nanxiang Li
  date: Apr 26, 2024.
  time: 4:30 p.m.
  location: Room CS119 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/TN3wdET7R1zx
    - title: Slides
      url:  /slides/RDMA.pdf
- title: "RainbowCake: Mitigating Cold-starts in Serverless with Layer-wise Container Caching and Sharing"
  conf: "ASPLOS'24"
  presenter: Haodong Tian
  date: Apr 19, 2024.
  time: 4:30 p.m.
  location: Room CS119 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/XRwuCpsUWtSL
    - title: Slides
      url: /slides/RainbowCake.pdf
- title: "Zeus: Understanding and Optimizing GPU Energy Consumption of DNN Training"
  conf: "NSDI'23"
  presenter: Chenyu Lu
  date: Apr 12, 2024.
  time: 4:30 p.m.
  location: Room CS119 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/0L7DNrSbZnoW
    - title: Slides
      url: /slides/zeus.pdf
- title: "PockEngine: Sparse and Efficient Fine-tuning in a Pocket"
  conf: "Micro'23"
  presenter: Mengyang Liu
  date: Mar 31, 2024.
  time: 7:30 p.m.
  location: Room CS119 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/cdhBgkQyD2E6
    - title: Slides
      url: /slides/PockEngine.pdf
- title: "Liquid: Intelligent Resource Estimation and Network-Efficient Scheduling for Deep Learning Jobs on DistributeGPU Clusters"
  conf: "TPDS'22"
  presenter: Haodong Tian
  date: Dec 18, 2023.
  time: 1:30 p.m.
  location: Room CS413 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/2gWGpIle5wj1
    - title: Slides
      url: /slides/Liquid.pdf
- title: "Astrea: Auto-Serverless Analytics Towards Cost-Efficiency and QoS-Awareness"
  conf: "TPDS'22"
  presenter: Haodong Tian
  date: Dec 11, 2023.
  time: 1:30 p.m.
  location: Cancelled
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/2gWGpIle5wj1
    - title: Slides
      url: https://seunic-my.sharepoint.cn/:p:/g/personal/213211315_seu_edu_cn/EbE_r4hcriZEn6EfYBz2ZtkBNB0HWAcI-a9JjzeFsEftAQ?e=HxL5Yk
- title: "Maximizing the Utilization of GPUs Used by Cloud Gaming through Adaptive Co-location with Combo"
  conf: "SoCC'23"
  presenter: Chenyu Lu
  date: Dec 04, 2023.
  time: 1:30 p.m.
  location: Room CS413 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/nLSQZtiSnUtD
    # - title: Slides
    #   url: /slides/Combo.pdf
- title: "Bolt: Bridging the Gap between Auto-tuners and Hardware-native Performance"
  conf: "MLSys'22"
  presenter: Guangtong Li
  date: Nov 27, 2023.
  time: 1:30 p.m.
  location: Room CS413 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/uJ0tczyl7dDs
    - title: Slides
      url: /slides/Bolt.pdf
- title: "SpaceEvo: Hardware-Friendly Search Space Design for Efficient INT8 Inference"
  conf: "ICCV'23"
  presenter: Ye Wan
  date: Nov 20, 2023.
  time: 1:30 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/Jus5fyooCImk
    - title: Slides
      url: /slides/SpaceEvo.pdf
      
- title: "Amanda: Unified Instrumentation Framework for Deep Neural Networks"
  conf: "ASPLOS'24"
  presenter: Mengyang Liu
  date: Nov 13, 2023.
  time: 1:30 p.m.
  location: Room CS413 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/pkXZDA0sv7rn
    - title: Slides
      url: /slides/Amanda.pdf

- title: "Golgi: Performance-Aware, Resource-Efficient Function Scheduling for Serverless Computing"
  conf: "SoCC'23"
  presenter: Haodong Tian
  date: Nov 6, 2023.
  time: 6:00 p.m.
  location: Room CS313 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/BG1i94P42jlG
    - title: Slides
      url: https://seunic-my.sharepoint.cn/:p:/g/personal/213211315_seu_edu_cn/ESmejV-0yrZPitd7ExUvVm0BgCBX9dOAb7Nxv-D7F1su2A?e=y1tWbq

- title: "Cost-effective On-device Continual Learning over Memory Hierarchy with Miro"
  conf: "Mobicom'23"
  presenter: Chenyu Lu
  date: Oct 31, 2023.
  time: 6:00 p.m.
  location: Room CS313 @ SEU
  links:
    - title: Slides
      url: /slides/miro.pdf

- title: "DepGraph: Towards Any Structural Pruning"
  conf: "CVPR'23"
  presenter: Guangtong Li
  date: Oct 24, 2023.
  time: 6:00 p.m.
  location: Room CS313 @ SEU
  links:
    - title: Slides
      url: /slides/DepGraph.pdf

- title: "NN-Stretch: Automatic Neural Network Branching for Parallel Inference on Heterogeneous Multi-Processors"
  conf: "Mobisys'23"
  presenter: Ye Wan
  date: Oct 17, 2023.
  time: 6:00 p.m.
  location: Room CS413 @ SEU
  links:
    - title: Slides
      url: /slides/NN-Stretch.pdf

- title: "LUT-NN: Empower Efficient Neural Network Inference with Centroid Learning and Table Lookup"
  conf: "MobiCom'23"
  presenter: Mengyang Liu
  date: Oct 15, 2023.
  time: 7:00 p.m.
  location: Room CS364 @ SEU
  links:
    - title: Slides
      url: /slides/LUT-NN.pdf

- title: "AQUATOPE: QoS-and-Uncertainty-Aware Resource Management for Multi-stage Serverless Workflows"
  conf: "ASPLOS'23"
  presenter: Haodong Tian
  date: Sep 26, 2023.
  time: 6:00 p.m.
  location: Room CS413 @ SEU
  links:
    - title: Slides
      url: /slides/AQUATOPE.pdf

- title: "ElasticTrainer: Speeding Up On-Device Training with Runtime Elastic Tensor Selection"
  conf: "Mobisys'23"
  presenter: Chenyu Lu
  date: June 29, 2023.
  time: 7:00 p.m.
  location: Room CS313 @ SEU & Online
  links:
    - title: TecentMeeting
      url: https://meeting.tencent.com/dm/kBz2Zw9Ne8sx
    - title: Slides
      url: /slides/ElasticTrainer.pdf

- title: "INFless: A Native Serverless System for Low-Latency, High-Throughput Inference"
  conf: "ASPLOS'22"
  presenter: Guangtong Li
  date: June 15, 2023.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TecentMeeting
      url: https://meeting.tencent.com/dm/tcI8MDYCn5zO
    - title: Slides
      url: /slides/INFless.pdf

- title: "ConvReLU++: Reference-based Lossless Acceleration of Conv-ReLU Operations on Mobile CPU"
  conf: "Mobisys'23"
  presenter: Ye Wan
  date: June 8, 2023.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TecentMeeting
      url: https://meeting.tencent.com/dm/GIZlZUew5kj5
    - title: Slides
      url: /slides/ConvRelu++.pdf

- title: "BeeHive: Sub-second Elasticity for Web Services with Semi-FaaS Execution"
  conf: "ASPLOS'23"
  presenter: Haodong Tian
  date: June 1, 2023.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TecentMeeting
      url: https://meeting.tencent.com/dm/GIZlZUew5kj5
    - title: Slides
      url: /slides/BeeHive.pdf

- title: "Understanding and Optimizing Deep Learning Cold-Start Latency on Edge Devices"
  conf: "MobiSys'23"
  presenter: Mengyang Liu
  date: May 25, 2023.
  time: 7:00 p.m.
  location: Room CS364 @ SEU & Online
  links:
    - title: TecentMeeting
      url: https://meeting.tencent.com/dm/vtnLMBunSfXU
    - title: Slides
      url: /slides/NNV12.pdf

- title: "ModelKeeper: Accelerating DNN Training via Automated Training Warmup"
  conf: "NSDI'23"
  presenter: Chenyu Lu
  date: Apr 13, 2023.
  time: 7:00 p.m.
  location: Room CS364 @ SEU & Online
  links:
    - title: TecentMeeting
      url: https://meeting.tencent.com/dm/6fPisSgvNOXv
    - title: Slides
      url: /slides/ModelKeeper.pdf

- title: "AStitch: Enabling a New Multi-dimensional Optimization Space for Memory-Intensive ML Training and Inferencon Modern SIMT Architectures"
  conf: "ASPLOS'22"
  presenter: Guangtong Li
  date: Mar 30, 2023.
  time: 7:00 p.m.
  location: Room CS364 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/yNGi2Nxl94go
    - title: Slides
      url: /slides/AStitch.pdf

- title: "Hyperion: A Generic and Distributed Mobile Offloading Framework on OpenCL"
  conf: "Sensys'22"
  presenter: Ye Wan
  date: Mar 23, 2023.
  time: 7:00 p.m.
  location: Room CS364 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/81KneO3hsY4j
    - title: Slides
      url: /slides/Hyperion.pdf

- title: "ROLLER: Fast and Efficient Tensor Compilation for Deep Learning"
  conf: "OSDI'22"
  presenter: Haodong Tian
  date: Mar 16, 2023.
  time: 7:00 p.m.
  location: Room CS364 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/zqo5C6KTLUDi
    - title: Slides
      url: /slides/ROLLER.pdf

- title: "TLP: A Deep Learning-Based Cost Model for Tensor Program Tuning"
  conf: "ASPLOS'23"
  presenter: Mengyang Liu
  date: Mar 9, 2023.
  time: 7:00 p.m.
  location: Room CS364 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/gF9Ft3uO69PR
    - title: Slides
      url: /slides/TLP.pdf
- title: "BlastNet: Exploiting Duo-Blocks for Cross-Processor Real-Time DNN Inference"
  conf: "SenSys'22"
  presenter: Chenyu Lu
  date: Feb 27, 2023.
  time: 7:00 p.m.
  location: Room CS364 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/m37eOiuvurKe
    - title: Slides
      url: /slides/BlastNet.pdf
- title: "Cachew: Machine Learning Input Data Processing as a Service"
  conf: "ATC'22"
  presenter: Guangtong Li
  date: Feb 20, 2023.
  time: 7:00 p.m.
  location: Room CS364 @ SEU & Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/VMAxl6WX5SDt
    - title: Slides
      url: /slides/CacheW.pdf
- title: "Soter: Guarding Black-box Inference for General Neural Networks at the Edge"
  conf: "ATC'22"
  presenter: Ye Wan
  date: Feb 13, 2023.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/XamoSoFq9K08
    - title: Slides
      url: /slides/SOTER.pdf
- title: "Microsecond-scale Preemption for Concurrent GPU-accelerated DNN Inference"
  conf: "OSDI'22"
  presenter: Mengyang Liu
  date: Feb 7, 2023.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/oL97GlMJEADM
    - title: Slides
      url: /slides/REEF.pdf

- title: "Tetris: Memory-efficient Serverless Inference through Tensor Sharing"
  conf: "ATC'22"
  presenter: Haodong Tian
  date: Jan 30, 2023.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/rYCLuoA7EVSf
    - title: Slides
      url: /slides/Tetris.pdf

- title: "Serving Heterogeneous Machine Learning Models on Multi-GPU Servers with Spatio-Temporal Sharing"
  conf: "ATC'22"
  presenter: Chenyu Lu
  date: Jan 16, 2023.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/QItk9sCtnRMl
    - title: Slides
      url: /slides/Gpulet.pdf

- title: "Campo: Cost-Aware Performance Optimization for Mixed-Precision Neural Network Training"
  conf: "ATC'22"
  presenter: Guangtong Li
  date: Jan 9, 2023.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/3wejGnobNOHR
    - title: Slides
      url: /slides/Campo.pdf

- title: "Melon: Breaking the Memory Wall for Resource-Efficient On-Device Machine Learning"
  conf: "MobiSys'22"
  presenter: Ye Wan
  date: December 26, 2022.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/BkcWtYkIeqC3
    - title: Slides
      url: /slides/Melon.pdf


- title: "Romou: rapidly generate high-performance tensor kernels for mobile GPUs"
  conf: "MobiCom'22"
  presenter: Mengyang Liu
  date: December 19, 2022.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/uS6xPdn9NzCi
    - title: Slides
      url: /slides/Romou.pdf

- title: "Real-time neural network inference on extremely weak devices: agile offloading with explainable AI"
  conf: "MobiCom'22"
  presenter: Chenyu Lu
  date: December 5, 2022.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/1BKlQNoChOlt
    - title: Slides
      url: /slides/AgileNN.pdf

- title: "Band: coordinated multi-DNN inference on heterogeneous mobile processors"
  conf: "MobiSys'22"
  presenter: Guangtong Li
  date: November 28, 2022.
  time: 8:00 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/TUIsg858C5VV
    - title: Slides
      url: /slides/BAND.pdf

- title: "CoDL: Efficient CPU-GPU Co-Execution for Deep Learning Inference on Mobile Devices"
  conf: "MobiSys'22"
  presenter: Ye Wan
  date: November 21, 2022.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/ZMCR9ItoDoFt
    - title: Slides
      url: /slides/CoDL.pdf

- title: "nn-Meter: Towards Accurate Latency Prediction of Deep-Learning Model Inference on Diverse Edge Devices"
  conf: "MobiSys'21"
  presenter: Mengyang Liu
  date: November 14, 2022.
  time: 7:00 p.m.
  location: Online
  links:
    - title: TencentMeeting
      url: https://meeting.tencent.com/dm/6r5oKfu8QCZO
    - title: Slides
      url: /slides/nn-Meter.pdf
